### ISSUE TITLE
`Metainfo.parse_metainfo_from_dict(m)` modifies `m`

### ISSUE THREAD

**Issue by serverhorror** [genestack/python-client#269]
Hi,

I have (approximately) this piece of code:

```
class TestGeneStack(unittest.TestCase):
    def test_MetainfoFromDict(self):
        from genestack_client import Metainfo
        m = Metainfo()
        m.add_string("foo", "bar")
        m.add_string("foo", "narf")
        m.add_decimal("zord", 1.1)

        for elem in ["a", "b"]:
            # reliably bails out on the second element
            fMetaInfo = Metainfo.parse_metainfo_from_dict(m)
```

This is around here, these lines mess with the source dict. This is neither documented nor expected:

* https://github.com/genestack/python-client/blob/2cc975da061fe0524584d3922f0d66c846e1bf4a/genestack_client/genestack_metainfo.py#L319-L320

Here's the output:

```
test_MetainfoFromDict (tests.test_genestack_api.TestGeneStack) ... 0.23.0
ERROR
Traceback (most recent call last):
  File "C:\Python27\Lib\unittest\case.py", line 329, in run
    testMethod()
  File "c:\Users\marcherm\PythonCode\stool\tests\test_genestack_api.py", line 91, in test_MetainfoFromDict
    fMetaInfo = Metainfo.parse_metainfo_from_dict(m)
  File "C:\Users\marcherm\.virtualenvs\marcherm-lpGG1nbj\lib\site-packages\genestack_client\genestack_metainfo.py", line 314, in parse_metainfo_from_dict
    for scalar_value in map(cls._parse_scalar_value, source_dict[key]):
  File "C:\Users\marcherm\.virtualenvs\marcherm-lpGG1nbj\lib\site-packages\genestack_client\genestack_metainfo.py", line 320, in _parse_scalar_value
    java_type = source_dict.pop('type')
KeyError: 'type'

======================================================================
ERROR: test_MetainfoFromDict (tests.test_genestack_api.TestGeneStack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\marcherm\PythonCode\stool\tests\test_genestack_api.py", line 91, in test_MetainfoFromDict
    fMetaInfo = Metainfo.parse_metainfo_from_dict(m)
  File "C:\Users\marcherm\.virtualenvs\marcherm-lpGG1nbj\lib\site-packages\genestack_client\genestack_metainfo.py", line 314, in parse_metainfo_from_dict
    for scalar_value in map(cls._parse_scalar_value, source_dict[key]):
  File "C:\Users\marcherm\.virtualenvs\marcherm-lpGG1nbj\lib\site-packages\genestack_client\genestack_metainfo.py", line 320, in _parse_scalar_value
    java_type = source_dict.pop('type')
KeyError: 'type'

----------------------------------------------------------------------
Ran 1 test in 2.148s

FAILED (errors=1)
```

**Comment by genestack-solomatin** [comment]
Thank you for report, will fix soon.
