### ISSUE TITLE
pip installation shows errors

### ISSUE THREAD

**Issue by serverhorror** [genestack/python-client#282]
Hi,

I just found that the installation via pip throws a few errors. Doesn't look like they cause trouble as it only relates to the `wheel` and `clean` targets:

```
pip install 'https://github.com/genestack/python-client/archive/v0.24.0.tar.gz#egg=genestack-client-0.24.0'
```

```
Collecting genestack-client-0.24.0 from https://github.com/genestack/python-client/archive/v0.24.0.tar.gz#egg=genestack-client-0.24.0
  Downloading https://github.com/genestack/python-client/archive/v0.24.0.tar.gz (106kB)
    100% |████████████████████████████████| 112kB 414kB/s
  Running setup.py (path:/tmp/pip-install-L_p2VH/genestack-client-0.24.0/setup.py) egg_info for package genestack-client-0.24.0 produced metadata for project name genestack-
client. Fix your #egg=genestack-client-0.24.0 fragments.
Requirement already satisfied (use --upgrade to upgrade): genestack-client from https://github.com/genestack/python-client/archive/v0.24.0.tar.gz#egg=genestack-client-0.24.0
 in ./lib/python2.7/site-packages
Requirement already satisfied: keyring in ./lib/python2.7/site-packages (from genestack-client) (12.2.1)
Requirement already satisfied: requests in ./lib/python2.7/site-packages (from genestack-client) (2.18.4)
Requirement already satisfied: pyOpenSSL in ./lib/python2.7/site-packages (from genestack-client) (18.0.0)
Requirement already satisfied: entrypoints in ./lib/python2.7/site-packages (from keyring->genestack-client) (0.2.3)
Requirement already satisfied: secretstorage<3; (sys_platform == "linux2" or sys_platform == "linux") and python_version < "3.5" in ./lib/python2.7/site-packages (from keyri
ng->genestack-client) (2.3.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./lib/python2.7/site-packages (from requests->genestack-client) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python2.7/site-packages (from requests->genestack-client) (2018.4.16)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./lib/python2.7/site-packages (from requests->genestack-client) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in ./lib/python2.7/site-packages (from requests->genestack-client) (2.6)
Requirement already satisfied: cryptography>=2.2.1 in ./lib/python2.7/site-packages (from pyOpenSSL->genestack-client) (2.2.2)
Requirement already satisfied: six>=1.5.2 in ./lib/python2.7/site-packages (from pyOpenSSL->genestack-client) (1.11.0)
Requirement already satisfied: configparser>=3.5; python_version == "2.7" in ./lib/python2.7/site-packages (from entrypoints->keyring->genestack-client) (3.5.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in ./lib/python2.7/site-packages (from cryptography>=2.2.1->pyOpenSSL->genestack-client) (
1.11.5)
Requirement already satisfied: enum34; python_version < "3" in ./lib/python2.7/site-packages (from cryptography>=2.2.1->pyOpenSSL->genestack-client) (1.1.6)
Requirement already satisfied: ipaddress; python_version < "3" in ./lib/python2.7/site-packages (from cryptography>=2.2.1->pyOpenSSL->genestack-client) (1.0.22)
Requirement already satisfied: asn1crypto>=0.21.0 in ./lib/python2.7/site-packages (from cryptography>=2.2.1->pyOpenSSL->genestack-client) (0.24.0)
Requirement already satisfied: pycparser in ./lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.2.1->pyOpenSSL->genestac
k-client) (2.18)
Building wheels for collected packages: genestack-client, genestack-client
  Running setup.py bdist_wheel for genestack-client ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-5tmtTd/wheels/b9/d3/34/9e29e503a5414ac3059ef14cb7b8296677b5f7a49602a99d7d
  Running setup.py bdist_wheel for genestack-client ... error
  Complete output from command /home/marcherm/git/stool/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-L_p2VH/genestack-client/setup.py';f=getattr
(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-wxM_hC --python-tag cp2
7:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-install-L_p2VH/genestack-client/setup.py'

  ----------------------------------------
  Failed building wheel for genestack-client
  Running setup.py clean for genestack-client
  Complete output from command /home/marcherm/git/stool/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-L_p2VH/genestack-client/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-install-L_p2VH/genestack-client/setup.py'

  ----------------------------------------
  Failed cleaning build dir for genestack-client
Successfully built genestack-client
Failed to build genestack-client
```

**Comment by klas-genestack** [comment]
Looks like a `pip` bug to me: pypa/pip/issues/5271
