### ISSUE TITLE
Unknown locale during docs generation

### ISSUE THREAD

**Issue by olegs** [genestack/python-client#68]
I've downloaded genestack-python client `0.1.9` and tried to generate docs, however script failed with exception. 

```
oleg-laptop:genestack-client oleg$ pip install Sphinx sphinx-rtd-theme
Collecting Sphinx
  Downloading Sphinx-1.3.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 157kB/s 
Collecting sphinx-rtd-theme
  Downloading sphinx_rtd_theme-0.1.9-py2-none-any.whl (693kB)
    100% |████████████████████████████████| 696kB 287kB/s 
Collecting snowballstemmer>=1.1 (from Sphinx)
  Downloading snowballstemmer-1.2.0.tar.gz (49kB)
    100% |████████████████████████████████| 53kB 2.6MB/s 
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /Users/oleg/miniconda/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /Users/oleg/miniconda/lib/python2.7/site-packages (from Sphinx)
Collecting docutils>=0.11 (from Sphinx)
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 138kB/s 
Collecting babel>=1.3 (from Sphinx)
  Downloading Babel-2.1.1-py2.py3-none-any.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 60kB/s 
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /Users/oleg/miniconda/lib/python2.7/site-packages (from Sphinx)
Collecting alabaster<0.8,>=0.7 (from Sphinx)
  Downloading alabaster-0.7.6-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /Users/oleg/miniconda/lib/python2.7/site-packages (from babel>=1.3->Sphinx)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/oleg/miniconda/lib/python2.7/site-packages (from Jinja2>=2.3->Sphinx)
Building wheels for collected packages: snowballstemmer, docutils
  Running setup.py bdist_wheel for snowballstemmer
  Stored in directory: /Users/oleg/Library/Caches/pip/wheels/26/52/99/e0eb6b825c16715026ef290c13f4a0fbb86f1a5eab51bb10a0
  Running setup.py bdist_wheel for docutils
  Stored in directory: /Users/oleg/Library/Caches/pip/wheels/d5/32/4f/1347e8ac67071e8150a5dc69354a51a04ac065d0b48334f608
Successfully built snowballstemmer docutils
Installing collected packages: sphinx-rtd-theme, snowballstemmer, docutils, babel, alabaster, Sphinx
Successfully installed Sphinx-1.3.1 alabaster-0.7.6 babel-2.1.1 docutils-0.12 snowballstemmer-1.2.0 sphinx-rtd-theme-0.1.9
oleg-laptop:genestack-client oleg$ cd docs/
oleg-laptop:docs oleg$ make html
sphinx-build -b html -d build/doctrees   source build/html
Traceback (most recent call last):
  File "/Users/oleg/miniconda/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/Users/oleg/miniconda/lib/python2.7/site-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/Users/oleg/miniconda/lib/python2.7/site-packages/sphinx/__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "/Users/oleg/miniconda/lib/python2.7/site-packages/sphinx/cmdline.py", line 19, in <module>
    from docutils.utils import SystemMessage
  File "/Users/oleg/miniconda/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/Users/oleg/miniconda/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Users/oleg/miniconda/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Users/oleg/miniconda/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/oleg/miniconda/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by olegs** [comment]
Workaround:
Setup current variables on MacOS El Capitan:
```
export LAND=ru_RU.UTF8
export LC_ALL=ru_RU.UTF8
```

**Comment by klas-genestack** [comment]
It's not a workaround, it's a proper fix. `"UTF-8"` isn't a correct locale, it's just an encoding. Default locale should be `"C"`.

**Comment by olegs** [comment]
Here are the default for bash:
```
Last login: Tue Oct 20 12:10:18 on ttys001
oleg-laptop:docs oleg$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

`unset LC_CTYPE` helps.

**Comment by olegs** [comment]
Looks like a `Sphinx ` problem on OS El Capitan, closing the issue.
